### ISSUE TITLE
ENV is destroying the current PATH 

### ISSUE THREAD

**Issue by pik** [dock0/arch#9]
Example script: 

```
FROM dock0/arch 
RUN set -x; echo $PATH && mkdir /home/test
ENV PATH=$PATH:/home/test
RUN set -x; echo $PATH \
  && mkdir /home/test/foo
```

Output: 
```
Step 0 : FROM dock0/arch
 ---> f31939812291
Step 1 : RUN set -x; echo $PATH && mkdir /home/test
 ---> Using cache
 ---> 47d0028076ac
Step 2 : ENV PATH $PATH:/home/test
 ---> Using cache
 ---> d562fa0c6453
Step 3 : RUN set -x; echo $PATH   && mkdir /home/test/foo
 ---> Running in 0fea81983476
+ echo :/home/test
+ mkdir /home/test/foo
:/home/test
/bin/sh: mkdir: command not found
INFO[0000] The command [/bin/sh -c set -x; echo $PATH   && mkdir /home/test/foo] returned a non-zero code: 127 
```

**Comment by akerl** [comment]
This appears to be an issue with docker itself, not with my specific usage? In the ENV instruction, it's not expanding $PATH, so "PATH=$PATH:/home/test" expands to "PATH=:/home/test" and mkdir is no longer in PATH.

I'm not sure what the actual end goal is here, but it's probably you want to be using absolute pathing for commands in a Dockerfile for maximum sanity.

**Comment by pik** [comment]
> This appears to be an issue with docker itself, not with my specific usage?

I tested with ubuntu and centOS images which are able to build this correctly.

**Comment by akerl** [comment]
Apologies, I meant "It's not in the current env, so it expands to "" rather than what you'd expect.

Can you provide a Dockerfile that shows this working as expected so I can replicate?

**Comment by pik** [comment]
The weird thing is PATH is not empty in the current env (you can see the echo output when building with --no-cache). 


```
pik@my-computer~/d/arch-test> cat Dockerfile 
# archlinux for tests
FROM dock0/arch
RUN set -x; echo $PATH && mkdir /home/test
ENV PATH=$PATH:/home/test
RUN set -x; echo $PATH \
  && mkdir /home/test/foo
pik@my-computer~/d/arch-test> docker build --no-cache . 
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 
Step 0 : FROM dock0/arch
 ---> f31939812291
Step 1 : RUN set -x; echo $PATH && mkdir /home/test
 ---> Running in 7126ef8d67f5
+ echo /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ mkdir /home/test
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 ---> 59648b8c265c
Removing intermediate container 7126ef8d67f5
Step 2 : ENV PATH $PATH:/home/test
 ---> Running in 95b3c9d8d0b4
 ---> a492cfb17d76
Removing intermediate container 95b3c9d8d0b4
Step 3 : RUN set -x; echo $PATH   && mkdir /home/test/foo
 ---> Running in e6ba5df64229
+ echo :/home/test
+ mkdir /home/test/foo
:/home/test
/bin/sh: mkdir: command not found
INFO[0007] The command [/bin/sh -c set -x; echo $PATH   && mkdir /home/test/foo] returned a non-zero code: 127 

```

Below is a working build of an arch-image: 

```
pik@my-computer~/d/arch-test> cat Dockerfile 
# archlinux for tests
FROM nfnty/arch-mini
RUN set -x; echo $PATH && mkdir /home/test
ENV PATH=$PATH:/home/test
RUN set -x; echo $PATH \
  && mkdir /home/test/foo
pik@my-computer~/d/arch-test> docker build --no-cache . 
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 
Step 0 : FROM nfnty/arch-mini
 ---> 635c47b1c5e9
Step 1 : RUN set -x; echo $PATH && mkdir /home/test
 ---> Running in a3c302c3aaf4
/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
+ echo /usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
+ mkdir /home/test
 ---> ece43461c767
Removing intermediate container a3c302c3aaf4
Step 2 : ENV PATH $PATH:/home/test
 ---> Running in d8233fca70d1
 ---> 055f7521abc2
Removing intermediate container d8233fca70d1
Step 3 : RUN set -x; echo $PATH   && mkdir /home/test/foo
 ---> Running in dbb5bc2bbe75
+ echo /usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/test
/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/test
+ mkdir /home/test/foo
 ---> 60a3e8cf0a23
Removing intermediate container dbb5bc2bbe75
Successfully built 60a3e8cf0a23
pik@my-computer~/d/arch-test> 

```

**Comment by akerl** [comment]
Yea, that's what I was referring to: https://registry.hub.docker.com/u/nfnty/arch-mini/dockerfile/

They set PATH earlier in the Dockerfile, so it exists in Docker's ENV, and when you do ENV PATH=$PATH:/home/test it reuses the previous value.

In your "RUN" lines, you're invoking sh, and sh ensures $PATH is set. As such, "echo $PATH" shows a result in all cases.

**Comment by pik** [comment]
I'm not sure I understand. Why is ENV clobbering PATH when it comes to your build?

**Comment by akerl** [comment]
So when you do "ENV stuff=stuff' in a Dockerfile, it's not actually invoking a shell for that step. Any expansion of a variable in there is done by Docker itself, as a helpful gesture. It's been a while since I dug into the line in question, but it essentially looks for "$" in the line and checks if that matches any variables it knows about. By default, Docker's internal ENV list doesn't include anything

In the case of nfnty/arch-mini, *they* set ENV PATH=stuff earlier in the Dockerfile, so earlier on, they have `ENV PATH '/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl'`, and when you do `ENV PATH $PATH:/home/test`, it uses that variable (the one internal to Docker's understanding) to expand $PATH.

In the case of my Dockerfile, I don't set PATH, so when you do `ENV PATH $PATH:/home/test`, Docker looks in its internal mapping, has no entry for $PATH, and thus replaces it with an empty string.

The RUN commands you're doing are providing misleading information, because the shell *does* set PATH. That's at the shell level, within that specific command. So for `RUN set -x; echo $PATH && mkdir /home/test`, Docker spawns a /bin/sh process inside the container's namespaces and runs `set -x; echo $PATH && mkdir /home/test` there. One of the things /bin/sh does is define $PATH if it's not already provided, so it helpfully sets $PATH and then, at your command, echoes it back.

I suspect that what you've shown thus far is a proof of concept to demonstrate the issue you're hitting, rather than the initial problem you were trying to solve when you encountered this. Depending on the initial problem, you'd probably want to either use absolute paths for your Dockerfile commands, set ENV PATH to a base string before trying to further expand it, or set $PATH in a bashrc or similar file inside the filesystem itself.

**Comment by pik** [comment]
I see -- so $PATH doesn't source the environment from the shell but only from Docker's internal state. That's a surprising behaviour but I don't think it's related to your build - closing.
